sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: ""
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5t7VsyHaKLtkC7ZL89QD
    access-key-secret: upMASXyNqZAQ4acCXrn6J6wnGMLrwd
    bucket-name: webdev-sky
  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 10
